<?php
	include_once 'config.php';
	session_start();
	//include('lock.php');

	$today = date("Y-m-d", strtotime('today'));
	$today2 = date("l, d F, Y", strtotime('today'));

	$_SESSION['today_dt_session'] = $today;
	$user=$_SESSION['username'];
	$s1=$_SESSION['studid1'];
	$s2=$_SESSION['stnd1'];
	$s3=$_SESSION['grp1'];	
	$s4=$_SESSION['btch1'];
	$s5=$_SESSION['sid'];
	$u5 = $_SESSION['uname'];
	$board1 = $_SESSION['board'];
	$branch = $_SESSION['branch'];
	
?>
<!doctype html>
<html>
	<head>
		<title>Welcome <?php echo $u5 ?></title>
		
		<SCRIPT type="text/javascript">
		  
		</SCRIPT>
		
		<link rel="shortcut icon" href="http://targetstudy.com/files/img/17/6957/L_17974.gif" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<style>
			label.custom-select {
				position: relative;
				display: inline-block;

			}
				.custom-select select {
					display: inline-block;
					padding: 4px 3px 3px 5px;
					margin: 0;
					font: inherit;
					outline:none; /* remove focus ring from Webkit */
					line-height: 1.2;
					background: #CCC;
					color:RED;
					border:0;
				}
				/* Select arrow styling */
				.custom-select:after {
					position: absolute;
					top: 0;
					right: 0;
					bottom: 0;
					font-size: 70%;
					line-height: 30px;
					padding: 0 7px;
					background: #000;
					color: red;
				}
				.no-pointer-events .custom-select:after {
					content: none;
				}
		</style>
		<style type="text/css" media="screen">
	
			html, body	{ height:100%; }
			body { margin:0; padding-left: .5em; overflow:auto; }
			#flashContent { display:none; }
			#sortable1, #sortable2 { list-style-type: none; margin: 0; padding: 0 0 2.5em; float: left; margin-right: 15px; }
			#sortable1 li, #sortable2 li { margin: 0 5px 5px 5px; padding: 5px; font-size: 1.2em; width: 200px; }
			
			
			#feedback { font-size: 1.4em; }
			#chap1, #chap2 { list-style-type: none; margin: 0; padding: 0; float: left; margin-right: 10px; background: #CEC8C8; padding: 5px; width: 235px;}
			#chap1 li, #chap2 li { margin: 5px; padding: 5px; font-size: 0.8em; text-align:left;  }
			#top1, #top2, #top3 { list-style-type: none; margin: 0; padding: 0; float: left; margin-right: 10px; background: #CEC8C8; padding: 5px; width: 235px;}
			#top1 li, #top2 li, #top3 li { margin: 5px; padding: 5px; font-size: 0.8em;  }
			#top1 li, #top2 li, #top3 li { background:#ddd; cursor:pointer; text-decoration:underline; text-align:left; }
			
		</style>
		
		<style name="xyz">
			
			table{
				width:200px;
				margin:0 auto;
				background-color:#eee;
				text-align:center;
				cursor:pointer;
			}
			th{
				background-color:#333;
				color:#FFF;
			}
			div#lyrics{
				width:300px;
				height:20px;
				background-color:#7C8698;
				position:absolute;
				left:30px;
				padding:8px;
				
			}
			#colorstrip{
			width: 100%; height: 22px;
			border-style: solid;
			border-color: white;
			background-color: #FFAA44;
			line-height: 20px;
			vertical-align: center;
			text-align:center;
			padding-top:5px;
		}
		</style>
		<style type="text/css">
		.classname {
			-moz-box-shadow:inset 0px 0px 0px 0px #ffffff;
			-webkit-box-shadow:inset 0px 0px 0px 0px #ffffff;
			box-shadow:inset 0px 0px 0px 0px #ffffff;
			background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );
			background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );
			filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');
			background-color:#ededed;
			-moz-border-radius:24px;
			-webkit-border-radius:24px;
			border-radius:24px;
			border:3px solid #dcdcdc;
			display:inline-block;
			color:#777777;
			font-family:arial;
			font-size:13px;
			font-weight:bold;
			padding:3px 10px;
			text-decoration:none;
			text-shadow:1px 1px 0px #ffffff;
		}.classname:hover {
			background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );
			background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );
			filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');
			background-color:#dfdfdf;
		}.classname:active {
			position:relative;
			top:1px;
		}
		/* This imageless css button was generated by CSSButtonGenerator.com */
		</style>
		<!--  It is Disabled to Right Click...  -->
		<script language="javascript"
			type="text/javascript"
			src="js/jquery.min.js">
		</script>
		<script type="text/javascript" language="javascript">
			$(function() {
		 
				$(this).bind("contextmenu", function(e) {
	 
					e.preventDefault();
	 
				});
		 
			});
		</script>
		
		<link rel="stylesheet" type="text/css" media="screen" href="css/jquery-ui-1.8.2.custom.css" />
		<link rel="stylesheet" type="text/css" media="screen" href="css/ui.jqgrid.css" />
		<script src="js/jquery-1.7.2.min.js" type="text/javascript"></script>
		<script src="js/grid.locale-en.js" type="text/javascript"></script>
		<script src="js/jquery.jqGrid.min.js" type="text/javascript"></script>
		
		<!--  Above Disabled to Right Click...  -->
			
		<link rel="stylesheet" href="css/bg.css" />  
		<link rel="stylesheet" href="css/jquery-ui.css" />
		<link rel="stylesheet" href="css/demo.css" />
		<link rel="stylesheet" type="text/css" media="screen" href="css/ui.jqgrid.css" />
		<link rel="stylesheet" type="text/css" href="css/flexpaper.css" />
		
		<script src="js/jquery-1.8.3.js"></script>
		<script src="js/jquery-ui.js"></script>
		<script type="text/javascript" src="js/flexpaper.js"> </script> 
		<!--<script type="text/javascript" src="js/jquery.min.js"> </script>	-->
		<script type="text/javascript" src="js/flexpaper_handlers.js"> </script>
		<script type="text/javascript" src="js/flexpaper_handlers_debug.js"> </script>
		
		<script language="javascript" type="text/javascript" src="js/jquery.flot.js"></script>
		<script language="javascript" type="text/javascript" src="js/jquery.flot.threshold.js"></script>
		
		<!-- five star -->
		<script type="text/javascript" src="lib/jquery.raty.min.js"></script>
		
		<!--	Timer  -->
		<link rel="stylesheet" href="css/styles2.css" />
		<script src="js/countdown.js"></script>
		<script src="js/moment.js"></script>
		<!--	Timer Finish...  -->
		
		<!-- jqgrid-->
		<!-- JQ Grid JS and CSS  session  	
			<link rel="stylesheet" type="text/css" media="screen" href="jq_grid/jquery-ui-1.8.2.custom.css" /> -->
			<link rel="stylesheet" type="text/css" media="screen" href="jq_grid/ui.jqgrid.css" />
		
	<!--	<script src="js/jquery-1.7.2.min.js" type="jq_grid/javascript"></script>	-->
			<script src="js/grid.locale-en.js" type="jq_grid/javascript"></script>
			<script src="js/jquery.jqGrid.min.js" type="jq_grid/javascript"></script>
		
		
	<!-- Date and Time	-->
		<script type="text/javascript" src="js/date_time.js"></script>
		
		
		<script> 
		$(document).ready(function(){
		
			var filename="";
			var uid=<?php echo $s1; ?>;
			function getContent(filename, selectboxid)
			{
				$.ajax({
					url: filename,
					type: 'GET',
					dataType: 'html',
					
					success: function(data, textStatus, xhr) {
						var strtemp = "$('#" + selectboxid + "').html(data)";
						eval(strtemp);
						//alert(data);
					},
				});									
			}
			$('#tt').click(function()
			{
				filename="parent/1_set_time_table.php?uid="+uid;
				getContent(filename,"time_set");
			});
			$('#pr').click(function()
			{
				filename="parent/6_test_score.php";
				//alert(filename);
				getContent(filename,"progress_report");
			});
			$('#fe').click(function()
			{
				filename="parent/3_forth_coming_ass.php";
				//alert(filename);
				getContent(filename,"forth_coming_examination");
				
			});
			$('#fa').click(function()
			{
				filename="parent/4_forth_coming_ass.php";
				//alert(filename);
				getContent(filename,"forth_coming_assignment");
			});
			$('#ha').click(function()
			{
				filename="parent/5_history_assignment.php";
				getContent(filename,"history_assignment");
			});
			$('#at').click(function()
			{
				alert("time table call");
			
			});
			$('#dr').click(function()
			{
				filename="parent_dignostics.php";
				getContent(filename,"dig_report");
			});
		});
		</script> 
		 <script>
			$(function() {
			
			$( "#tabs" ).tabs().addClass( "ui-tabs-vertical ui-helper-clearfix" );
			$( "#tabs li" ).removeClass( "ui-corner-top" ).addClass( "ui-corner-left" );
			
			});
		</script>		
	</head>
	<body oncontextmenu="return false">
		<?php 
			
			$result=mysql_query("SELECT NAME AS group_name FROM `group` WHERE id=".$s3);
			$result1=mysql_query("Select name as batch_name from batch where id=".$s4);
			$result2=mysql_query("SELECT NAME as standard_name FROM standard WHERE id=".$s2);
			
			$row=mysql_fetch_array($result);
			if($row)
			{
				$grp1 = $row['group_name'];
			}
		
			$row1=mysql_fetch_array($result1);
			if($row1)
			{
				$btch1 = $row1['batch_name'];
			}	
			$row2=mysql_fetch_array($result2);
			if($row2)
			{
				$std2 = $row2['standard_name'];
			}	
		?>
			<?php require 'header3.php'; ?>

			<div><h3><b>
				Welcome Parent !
				</b></h3>
			</div>
			
			<div>
				<?php echo  "Student ID : ".$s1;
				echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
				echo "Student Standard: ".$std2. "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Group : ".$grp1. "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Batch Name : ".$btch1;
				?>
			</div> 
			</div>
	<table style="width:1100px;" align="left">
		<tr>
			<td style="width:100%;">	<!--	style="border:1px solid blue;"	-->
				<table style="width:100%;">
					<tr>
						<td style="width:80%;">
						
							<div id="tabs" style="height: 610px;">
								
								<ul id="menubar_ul">
									
									<li><a href="#tabs-3" id="fe" style="width:150px;"><font size="1"><b>Forthcoming Examination</b></font></a></li>
									
									<li><a href="#tabs-4" id="fa" style="width:230px;"><font size="1"><b>Forthcoming Assignment Submission</b></font></a></li>
									
									<li><a href="#tabs-5" id="ha" style="width:130px;"><font size="1"><b>History of Assignment</b></font></a></li>
									
									<!--<li><a href="#tabs-6" id="at" style="width:80px;"><font size="1"><b>Take a Test</b></font></a></li>-->
									<li><a href="#tabs-7" id="dr" style="width:120px;"><font size="1"><b>Diagnostics Report</b></font></a></li>
									<li><a href="#tabs-1" id="tt" style="width:105px;"><font size="1"><b>Today's Time Table</b></font></a></li>
									
								</ul>
								<div class="tabs-spacer" align="left">
									<div id="tabs-1" name="tt">
										<div id="time_set">
										</div>
									</div>
									<div id="tabs-3" name="fe">
										<table id="forth_coming_examination" style="width:800px;">
											
										</table>
									</div>
									<div id="tabs-4" name="fa">
										<table id="forth_coming_assignment" style="width:800px;">
											
										</table>
									</div>
									<div id="tabs-5" name="ha">
										<div id="history_assignment" style="padding-top:5px;width:1000px;height:520px;overflow-y: scroll;border-style:solid;border-width:2px;">
										</div>
									</div>
									
									<div id="tabs-6" name="at">
									</div>
									<div id="tabs-7" name="dr">
										<div id="dig_report">
										</div>
									</div>
								</div>
							</div>	
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td>
				<label>Copyright &copy Edutech Educational Services Pvt. Ltd. </label>
			</td>
		</tr>
	</table>
	<?php
		include 'conn_close.php';
	?>
	</body>
</html>