<?php

	include("config.php");
	//include('lock.php');
	session_start();
	$s5=$_SESSION['login_id'];
	$s3=$_SESSION['group_id'];
	$sname=$_SESSION['student_name'];
	$today = date("Y-m-d", strtotime('today'));
	$today2 = date("l, d F, Y", strtotime('today'));
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Welcome  <?php echo "Parent !" ?></title>
			<link rel="shortcut icon" href="images/Edutechheader.ico" />
			
			<link href="css/style2.css" rel="stylesheet" type="text/css" />
			<link href="css/style.css" rel="stylesheet" type="text/css"  media="screen" />
		
		<!-- JQ Grid JS and CSS  session   -->	
			<link rel="stylesheet" type="text/css" media="screen" href="css/jquery-ui-1.8.2.custom.css" />
			<link rel="stylesheet" type="text/css" media="screen" href="css/ui.jqgrid.css" />
		
			<script src="js/jquery-1.7.2.min.js" type="text/javascript"></script>
			<script src="js/grid.locale-en.js" type="text/javascript"></script>
			<script src="js/jquery.jqGrid.min.js" type="text/javascript"></script>
			
			<!-- flexpaper-->
			<link rel="stylesheet" type="text/css" href="css/flexpaper.css" />
			<script type="text/javascript" src="js/flexpaper.js"> </script> 
<!--	<script type="text/javascript" src="js/jquery.min.js"> </script>	-->
		<script type="text/javascript" src="js/flexpaper_handlers.js"> </script>
		<script type="text/javascript" src="js/flexpaper_handlers_debug.js"> </script>
		
		<!-- END-- >
		<!--  Float Chart -->
			<script language="javascript" type="text/javascript" src="js/jquery.flot.js"></script>
			<script language="javascript" type="text/javascript" src="js/jquery.flot.threshold.js"></script>
		
			<link rel="stylesheet" href="css/jquery-ui.css" />
			<script src="js/jquery-ui.js"></script>
		
			<link type="text/css" rel="stylesheet" href="css/multipleselectbox.css" />
			<script type="text/javascript" src="js/jquery.multipleselectbox-src.js"></script>
		
			<script src="js/jquery.watermarkinput.js" type="text/javascript"></script>
			<link href="menu.css" rel="stylesheet" type="text/css" />
		<style type="text/css">
			html, body {
				margin: 0;
				padding: 0;
			}
			
			#placeholder2 div.xAxis div.tickLabel 
			{    
				transform: rotate(-90deg);
				-ms-transform:rotate(-90deg); /* IE 9 */
				-moz-transform:rotate(-70deg); /* Firefox */
				padding-top:2px;
				-webkit-transform:rotate(-90deg); /* Safari and Chrome */
				-o-transform:rotate(-90deg); /* Opera */
				/*rotation-point:50% 50%;*/ /* CSS3 */
				/*rotation:270deg;*/ /* CSS3 */
			}
		</style>
		<style type="text/css">
		.classname {
			-moz-box-shadow:inset 0px 0px 0px 0px #ffffff;
			-webkit-box-shadow:inset 0px 0px 0px 0px #ffffff;
			box-shadow:inset 0px 0px 0px 0px #ffffff;
			background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );
			background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );
			filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');
			background-color:#ededed;
			-moz-border-radius:24px;
			-webkit-border-radius:24px;
			border-radius:24px;
			border:3px solid #dcdcdc;
			display:inline-block;
			color:#777777;
			font-family:arial;
			font-size:13px;
			font-weight:bold;
			padding:3px 10px;
			text-decoration:none;
			text-shadow:1px 1px 0px #ffffff;
		}.classname:hover {
			background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );
			background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );
			filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');
			background-color:#dfdfdf;
		}.classname:active {
			position:relative;
			top:1px;
		}
		/* This imageless css button was generated by CSSButtonGenerator.com */
		</style>
		<style type="text/css">
			select {
			padding:3px;
			margin: 0;
			-webkit-border-radius:4px;
			-moz-border-radius:4px;
			border-radius:4px;
			-webkit-box-shadow: 0 3px 0 #ccc, 0 -1px #fff inset;
			-moz-box-shadow: 0 3px 0 #ccc, 0 -1px #fff inset;
			box-shadow: 0 3px 0 #ccc, 0 -1px #fff inset;
			background: #f8f8f8;
			color:#888;
			border:none;
			outline:none;
			display: inline-block;
			-webkit-appearance:none;
			-moz-appearance:none;
			appearance:none;
			cursor:pointer;
		}
		</style>
		<script type="text/javascript">
			$(function (){ 
				var user_id='<?php echo $s5; ?>';
				var select_type_id='34',test_id_batch="";
				//alert("hai");
				$('#sb').click(function(){
					$("#rp,#sn,#qp,#test_id_with_date").empty();
					sb=$("#sb").val();
					if(sb==14){ sb1="Biology"; sbb1="BIO";}
					else if(sb==15){ sb1="Maths"; sbb1="MAT";}
					else if(sb==16){ sb1="Physics"; sbb1="PHY";}
					else if(sb==17){ sb1="Chemistry"; sbb1="CHE";}
					else if(sb==18){ sb1="Science"; sbb1="SCI";}
					else if(sb==19){ sb1="English"; sbb1="ENG";}
					else if(sb==20){ sb1="Mock"; sbb1="MOC";}
					else if(sb==22){ sb1="SocialScience"; sbb1="S.S";}
					
					filename="forth2/11_get_test_id_with_Date.php?sb="+sbb1+"&user_id="+user_id;
					//alert(filename);
					getContent(filename,"test_id_with_date");
					//filename="forth2/12_faculty_display.php?bt="+bt+"&sb="+sb;
					//alert(filename);
					//getContent(filename,"teachers_name");
				});
				$('#test_id_with_date').click(function(){
					$("#rp,#sn,#qp").empty();
					test_id_with_date=$("#test_id_with_date").val();
					//alert(test_id_with_date);
					var mySplitResult = test_id_with_date.split("-");
					st_id=mySplitResult[0];
					name_id=mySplitResult[1];
					test_date_id=mySplitResult[2];
					bt_name=mySplitResult[3];
					bt_id=mySplitResult[4];
					//alert(bt_name);
					dg_get=st_id+name_id+test_date_id;
					//alert(dg_get);
					//alert(test_date_id);
					if(select_type_id == '34')
					{
						type_dir="ConceptWiseReport";
						tp='_C';
					}
					else
					{
						type_dir="QuestionWiseReport";
						tp='_Q';
					}
					test_id_batch=test_date_id+"_"+bt_name+tp;
					path="R:\\FacultyAnalysisReport\\"+type_dir+"\\"+test_id_batch;
					filename = "forth2/copy_location.php?output="+path+"&mn="+test_id_batch;
					//alert(filename);
					$.ajax({
						url: filename,
						type: 'GET',
						dataType: 'html',
						
						success: function(data, textStatus, xhr) {
							//alert(data);
						},
					});
					filename="forth2/10_get_que_paper.php?dg_get="+dg_get+"&user_id1="+user_id;
					//alert(filename);
					getContent(filename,"qp");
					filename="forth2/10_get_sol_paper.php?dg_get="+dg_get+"&user_id1="+user_id;
					//alert(filename);
					getContent(filename,"sn");
					filename="forth2/10_get_report_paper.php?dg_get="+dg_get+"&user_id1="+user_id;
					//alert(filename);
					getContent(filename,"rp");
				});
				$('#qp').click(function(){
					qp=$("#qp").val();
					//alert(qp);
					callFlexPaperDocViewer(qp);
				});
				$('#sn').click(function(){
					sn=$("#sn").val();
					//alert(qp);
					callFlexPaperDocViewer(sn);
				});
				$('#rp').click(function(){
					rp=$("#rp").val();
					//alert(qp);
					callFlexPaperDocViewer(rp);
				});
				$('input[type="radio"][name="v_a_r"]').click(function(){
					
					var type_id = $("input[type='radio'][name='v_a_r']:checked");
					if (type_id.length > 0)
					select_type_id = type_id.val();
					//alert(select_type_id);
					if(select_type_id == '34')
					{
						/*filename = "view_analysis_report/4_get_student_list.php?batch_id="+batch_id+"&sub="+sub+"&test_date="+test_date+"&type="+select_type_id;
						getContent(filename, "test_id");*/
					}
					else if(select_type_id == '35')
					{
						/*filename = "view_analysis_report/4_get_student_list.php?batch_id="+batch_id+"&sub="+sub+"&test_date="+test_date+"&type="+select_type_id;
						getContent(filename, "test_id");*/
						
					}
				});
				function getInsert(filename)
				{
					$.ajax({
						url: filename,
						type: 'GET',
						dataType: 'html',
						
						success: function(data, textStatus, xhr) {
							alert(data);
						},
					});
				}
				function getContent(filename, selectboxid)
				{
					$.ajax({
						url: filename,
						type: 'GET',
						dataType: 'html',
						
						success: function(data, textStatus, xhr) {
							var strtemp = "$('#" + selectboxid + "').html(data)";
							eval(strtemp);
							//alert(data);
						},
					});									
				}
			});
		</script>
		<style>
			*
			{
				margin:0;padding:0;    
			}
			html,body
			{
				height:100%;
				width:100%;
			}
			body
			{
				display:table;
			}
			.row
			{
				width: 100%;
				background: #0174DF;
				display:table-row;

			}
			.container
			{
				background: pink;
				height:100%; 
				
			}
			.content {
				display: block;
				height:95%;
				box-sizing: border-box;
			}
			footer 
			{ 
				position: fixed; 
				bottom: 0; 
				left: 0; 
				background: white;
				height: 40px;
				line-height: 40px;
				width: 100%;
				text-align: center;
			}
			.sidebar{
				float:left;
				background:green;
				height:100%;
				width:10%;
			}
			.contents{
				float:left;
				background:#E0ECF8;
				height:655px;
				width:100%;
				overflow:auto;
			}
			.contents2{
				float:left;
				background:#E0ECF8;
				height:5%;
				width:100%;
				overflow:auto;
			}
		</style>
	</head>
	<body bgcolor="white">
		<div class="row">
			<table>
				<tr>
					<td style='float:left;'>
						<?php require 'adlp.php'; ?>
					</td>
				</tr>
				<tr>
					<td style='float:left;'>
						<?php require 'menubar.php'; ?>
					</td>
				</tr>
			</table>
		</div>
		<div class="row container">
			<div class="content">
				<div class="contents2">
					<table>
						<tr>
							<td style='float:left;'>
								<div id="wl" style="width:1000px;">
									<div style="padding-left:5px;padding-top:5px;font-size:12px;text-transform: capitalize;">
										<b>
										Welcome <?php echo "&nbsp;&nbsp;&nbsp;Parent &nbsp;!"."&nbsp;&nbsp;&nbsp;&nbsp;".$sname;
										
										//."User  ID : ".$login_session_id; 
										?>
										</b>
									</div>
								</div>
							</td>
						</tr>
					</table>
				</div>
				<div class="contents" style='border:solid 0px;"'>
					<table style="padding-top:0px;border:solid 0px;width:100%;height:20px;">
						<tr>
							<td style="background-color:#3366FF;border:solid 0px;">
								<!--<image src="images/ar1.png"/>--><label style="color:white;font-size:10px;"><b>Dignostic Reports</b></label>
							</td>
						</tr>
					</table>
					<div class="lg-container"  style="border: 0px solid black;width: 100%;height:600px;">
							<div style="width: 100%;height:135px;border: 0px solid black;">
								<table width="50%" style="float:left;border: 0px solid black;">
									<tr style='background-color:#3366FF;'>
										<td style='color:white;'><b>Subject </b></td>
										<td style='color:white;'><b>Test-ID </b></td>
										<td style='color:white;'><b>Question Paper </b></td>
										<td style='color:white;'><b>Solution </b></td>
										<td style='color:white;'><b>Dignostic Report </b></td>
									</tr>
									<tr>
										<td><select id="sb" name="sb" size="6" style="width:95px;">
										<?php
										
											if($s3 == '9')
											{
												$result=mysql_query("SELECT id,NAME FROM detail WHERE id IN(14,16,17,18)");
											}
											else if($s3 == '10')
											{
												$result=mysql_query("SELECT id,NAME FROM detail WHERE id IN(15,16,17,18)");
											}
											else if($s3 == '11')
											{
												$result=mysql_query("SELECT id,NAME FROM detail WHERE id IN(14,15,16,17)");
											}
											else if($s3 == '12')
											{
												$result=mysql_query("SELECT id,NAME FROM detail WHERE id IN(15,18)");
											}
											else if($s3 == '13')
											{
												$result=mysql_query("SELECT id,NAME FROM detail WHERE id IN(19,22)");
											}
											else if($s3 == '21')
											{
												$result=mysql_query("SELECT id,NAME FROM detail WHERE id IN(15,18,19,22)");
											}
											$rw = mysql_num_rows($result);
											if($rw == 0)
											{
												echo "<option value='0'>No Data Available.</option>";
											}
											else
											{
												while($row=mysql_fetch_array($result))
												{
													echo "<option value='$row[0]'>$row[1]</option>";
												}
											}
										?>
										</select>
										</td>
										<td><select id="test_id_with_date" name="test_id_with_date" size="6" style="width:165px;"/></td>
										<td><select id="qp" name="qp" size="6" style="width:150px;"/></td>
										<td><select id="sn" name="sn" size="6" style="width:150px;"/></td>
										<td><select id="rp" name="rp" size="6" style="width:165px;"/></td>
									</tr>
								</table>
							</div>
							<!--<div style="width: 100%;height:25px;border: 2px solid black;">
								<input id="1" type="radio" name="v_a_r" checked="checked" value="34"><label for="1">Concept wise difficulty analysis</label>
								<input id="2" type="radio" name="v_a_r" value="35"><label for="2">Question wise difficulty analysis</label>
								<!--<label id='teachers_name'>Faculty is : </label>
							</div>-->
							<div id="doc34" style="position:absolute;left:5px;top:340px;">
								<div id="documentViewer" class="flexpaper_viewer" style="border:solid 1px;width:730px;height:400px"></div>
								<script type="text/javascript">
									function getDocumentUrl(document){
										//alert(document);
										//alert("services/view.php?doc={doc}&format={format}&page={page}");
										return "services/view.php?doc={doc}&format={format}&page={page}".replace("{doc}",document);
									}
									function getDocQueryServiceUrl(document){
										return "services/swfsize.php?doc={doc}&page={page}".replace("{doc}",document);
									}
									var startDocument = "<?php if(isset($_GET["doc"])){echo $_GET["doc"];}else{?>paper_gen.pdf<?php } ?>";
									$('#documentViewer').FlexPaperViewer(
									 {
										config : {
											 DOC : escape(getDocumentUrl(startDocument)),
											 Scale : 0.6,
											 ZoomTransition : 'easeOut',
											 ZoomTime : 0.5,
											 ZoomInterval : 0.2,
											 FitPageOnLoad : false,
											 FitWidthOnLoad : true,
											 FullScreenAsMaxWindow : false,
											 ProgressiveLoading : false,
											 MinZoomSize : 0.2,
											 MaxZoomSize : 5,
											 SearchMatchAll : false,
											 InitViewMode : 'Portrait',
											 RenderingOrder : 'flash,html',

											 ViewModeToolsVisible : true,
											 ZoomToolsVisible : true,
											 NavToolsVisible : true,
											 CursorToolsVisible : true,
											 SearchToolsVisible : true,

											 DocSizeQueryService : 'services/swfsize.php?doc=' + startDocument,
											 jsDirectory : 'js/',
											 localeDirectory : 'locale/',

											 JSONDataType : 'jsonp',
											 key : '',

											 localeChain: 'en_US'

											 }}
									);
									
									//callFlexPaperDocViewer("Paper.pdf");
									
									function callFlexPaperDocViewer(startDocument1){
										//alert(startDocument1);
									
										$('#documentViewer').FlexPaperViewer({
											config : {

											 DOC : escape(getDocumentUrl(startDocument1)),
											 Scale : 0.6,
											 ZoomTransition : 'easeOut',
											 ZoomTime : 0.5,
											 ZoomInterval : 0.2,
											 FitPageOnLoad : false,
											 FitWidthOnLoad : true,
											 FullScreenAsMaxWindow : false,
											 ProgressiveLoading : false,
											 MinZoomSize : 0.2,
											 MaxZoomSize : 5,
											 SearchMatchAll : false,
											 InitViewMode : 'Portrait',
											 RenderingOrder : 'flash,html',

											 ViewModeToolsVisible : true,
											 ZoomToolsVisible : true,
											 NavToolsVisible : true,
											 CursorToolsVisible : true,
											 SearchToolsVisible : true,

											 DocSizeQueryService : 'services/swfsize.php?doc=' + startDocument1,
											 jsDirectory : 'js/',
											 localeDirectory : 'locale/',

											 JSONDataType : 'jsonp',
											 key : '',

											 localeChain: 'en_US'

											 }}
									);
									}
								</script>
							</div>
						</div>
				</div>
			</div>
		</div>
		<div>
			<?php require 'copy_right_file.php'; ?>
		</div>
	</body>
	<?php
		include 'conn_close.php';
	?>
</html>