<?php

	include_once 'config.php';

	session_start();
	include('lock.php');

	$today = date("Y-m-d", strtotime('today'));
	$today2 = date("l, d F, Y", strtotime('today'));

	$user=$_SESSION['username'];
	$s1=$_SESSION['studid1'];
	$s2=$_SESSION['stnd1'];
	$s3=$_SESSION['grp1'];	
	$s4=$_SESSION['btch1'];
	$s5=$_SESSION['sid'];
	$u5 = $_SESSION['uname'];
	$board1 = $_SESSION['board'];
	$branch = $_SESSION['branch'];
	
?>
<!doctype html>
<html>
	<head>
		<title>Welcome <?php echo $u5 ?></title>
		<link rel="shortcut icon" href="http://targetstudy.com/files/img/17/6957/L_17974.gif" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<style>
			label.custom-select {
				position: relative;
				display: inline-block;

			}
				.custom-select select {
					display: inline-block;
					padding: 4px 3px 3px 5px;
					margin: 0;
					font: inherit;
					outline:none; /* remove focus ring from Webkit */
					line-height: 1.2;
					background: #CCC;
					color:RED;
					border:0;
				}
				/* Select arrow styling */
				.custom-select:after {
					position: absolute;
					top: 0;
					right: 0;
					bottom: 0;
					font-size: 70%;
					line-height: 30px;
					padding: 0 7px;
					background: #000;
					color: red;
				}
				.no-pointer-events .custom-select:after {
					content: none;
				}
		</style>
		<style type="text/css" media="screen">
	
			html, body	{ height:100%; }
			body { margin:0; padding-left: .5em; overflow:auto; }
			#flashContent { display:none; }
			#sortable1, #sortable2 { list-style-type: none; margin: 0; padding: 0 0 2.5em; float: left; margin-right: 15px; }
			#sortable1 li, #sortable2 li { margin: 0 5px 5px 5px; padding: 5px; font-size: 1.2em; width: 200px; }
			
			
			#feedback { font-size: 1.4em; }
			#chap1, #chap2 { list-style-type: none; margin: 0; padding: 0; float: left; margin-right: 10px; background: #CEC8C8; padding: 5px; width: 235px;}
			#chap1 li, #chap2 li { margin: 5px; padding: 5px; font-size: 0.8em; text-align:left;  }
			#top1, #top2, #top3 { list-style-type: none; margin: 0; padding: 0; float: left; margin-right: 10px; background: #CEC8C8; padding: 5px; width: 235px;}
			#top1 li, #top2 li, #top3 li { margin: 5px; padding: 5px; font-size: 0.8em;  }
			#top1 li, #top2 li, #top3 li { background:#ddd; cursor:pointer; text-decoration:underline; text-align:left; }
			
		</style>
		
		<style name="xyz">
			
			table{
				width:200px;
				margin:0 auto;
				background-color:#eee;
				text-align:center;
				cursor:pointer;
			}
			th{
				background-color:#333;
				color:#FFF;
			}
			div#lyrics{
				width:300px;
				height:20px;
				background-color:#7C8698;
				position:absolute;
				left:30px;
				padding:8px;
				
			}
			#colorstrip{
			width: 100%; height: 22px;
			border-style: solid;
			border-color: white;
			background-color: #FFAA44;
			line-height: 20px;
			vertical-align: center;
			text-align:center;
			padding-top:5px;
		}
		</style>
		<style type="text/css">
		.classname {
			-moz-box-shadow:inset 0px 0px 0px 0px #ffffff;
			-webkit-box-shadow:inset 0px 0px 0px 0px #ffffff;
			box-shadow:inset 0px 0px 0px 0px #ffffff;
			background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) );
			background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% );
			filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf');
			background-color:#ededed;
			-moz-border-radius:24px;
			-webkit-border-radius:24px;
			border-radius:24px;
			border:3px solid #dcdcdc;
			display:inline-block;
			color:#777777;
			font-family:arial;
			font-size:13px;
			font-weight:bold;
			padding:3px 10px;
			text-decoration:none;
			text-shadow:1px 1px 0px #ffffff;
		}.classname:hover {
			background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) );
			background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% );
			filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed');
			background-color:#dfdfdf;
		}.classname:active {
			position:relative;
			top:1px;
		}
		/* This imageless css button was generated by CSSButtonGenerator.com */
		</style>
		<!--  It is Disabled to Right Click...  -->
		<script language="javascript"
			type="text/javascript"
			src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js">
		</script>
		<script type="text/javascript" language="javascript">
			$(function() {
		 
				$(this).bind("contextmenu", function(e) {
	 
					e.preventDefault();
	 
				});
		 
			});
		</script>
		
		<link rel="stylesheet" type="text/css" media="screen" href="css/jquery-ui-1.8.2.custom.css" />
		<link rel="stylesheet" type="text/css" media="screen" href="css/ui.jqgrid.css" />
		<script src="js/jquery-1.7.2.min.js" type="text/javascript"></script>
		<script src="js/grid.locale-en.js" type="text/javascript"></script>
		<script src="js/jquery.jqGrid.min.js" type="text/javascript"></script>
		
		
		
		
		<!--  Above Disabled to Right Click...  -->
			
		<link rel="stylesheet" href="css/bg.css" />  
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css" />
		<link rel="stylesheet" href="css/demo.css" />
		<link rel="stylesheet" type="text/css" media="screen" href="css/ui.jqgrid.css" />
		<link rel="stylesheet" type="text/css" href="css/flexpaper.css" />
		
		<script src="http://code.jquery.com/jquery-1.8.3.js"></script>
		<script src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
		<script type="text/javascript" src="js/flexpaper.js"> </script> 
		<!--<script type="text/javascript" src="js/jquery.min.js"> </script>	-->
		<script type="text/javascript" src="js/flexpaper_handlers.js"> </script>
		<script type="text/javascript" src="js/flexpaper_handlers_debug.js"> </script>
		
		<script language="javascript" type="text/javascript" src="js/jquery.flot.js"></script>
		<script language="javascript" type="text/javascript" src="js/jquery.flot.threshold.js"></script>
		
		<!-- jqgrid-->
		<script> 
		$(document).ready(function(){

		var groupid = "";
		var nm = "";
		var sl = "";
		var sub_id = "";
		var tl = "";
		
		var batch_assign = "";
		var personal_assign = "";
		var other_school = "";
		var previous_objective = "";
		var previous_subjective = "";
		var notes_id = "";
		var ck_omr = "";
		
		var tab = "";
		var filename = "";
		
		var bt_id=<?php echo $s4; ?>;
		var u_id=<?php echo $s5; ?>;
		var br_id=<?php echo $branch; ?>;
		
		$("#Show_OMR_Div").hide();
			
			/*window.addEventListener("keyup",kPress,false);
			function kPress(e)
			{ 
				var c=e.keyCode||e.charCode; 
				if (c==44) 
				{
					alert("print screen");
					Clipboard.Clear();
					return true;		
				}
			}*/			
			LoadBatchAssignmentsByDefault();
			function LoadBatchAssignmentsByDefault()
			{	
				
				tab = 1001;
			
				filename = "query/query.php?dt=1";
				getContent(filename,"s1");
				filename = "query/query2.php?dt=1";
				getContent(filename, "s3");
				filename = "query/query3.php?dt=1";
				getContent(filename, "s5");
				filename = "query/query4.php?dt=1";
				getContent(filename, "s7");
				filename = "query/query5.php?dt=1";
				getContent(filename, "s9");
				filename = "query/query6.php?dt=1";
				getContent(filename, "s11");
				filename = "query/query8.php?dt=1";
				getContent(filename, "s12");
				filename = "query/query7.php?dt=1";
				getContent(filename, "s13");
				filename = "query/query9.php?dt=a";
				getContent(filename,"s14");
			}
			function show_sdf_tools_plan()
			{
				$("#doc34").show();
				$("#plan").show();
			}
			
			getgroupsubjects(<?php echo $s3; ?>);
		
			function getgroupsubjects(groupid)
			{
				if(groupid === 9)
				{					
					$("#dp1,#do1,#dt1,#dtp1,#ntt1,#ds1").hide();
					$("#dp9,#do9,#dt9,#dtp9,#ntt9,#ds9").hide();
					$("#dp11,#do11,#dt11,#dtp11,#ntt11,#ds11").hide();
					$("#dp12,#do12,#dt12,#dtp12,#ntt12,#ds12").hide();
					
				}
				else if(groupid === 10)
				{
					$("#dp3,#do3,#dt3,#dtp3,#ntt3,#ds3").hide();
					$("#dp9,#do9,#dt9,#dtp9,#ntt9,#ds9").hide();
					$("#dp11,#do11,#dt11,#dtp11,#ntt11,#ds11").hide();
					$("#dp12,#do12,#dt12,#dtp12,#ntt12,#ds12").hide();
				}
				else if(groupid === 11)
				{								
					$("#dp9,#do9,#dt9,#dtp9,#ntt9,#ds9,#dds9").hide();
					$("#dp11,#do11,#dt11,#dtp11,#ntt11,#ds11,#dds11").hide();
					$("#dp12,#do12,#dt12,#dtp12,#ntt12,#ds12").hide();
				}
				else if(groupid === 12)
				{								
					$("#dp1,#do1,#dt1,#dtp1,#ntt1,#ds1").hide();
					$("#dp5,#do5,#dt5,#dtp5,#ntt5,#ds5").hide();
					$("#dp7,#do7,#dt7,#dtp7,#ntt7,#ds7").hide();
					$("#dp12,#do12,#dt12,#dtp12,#ntt12,#ds12").hide();
					$("#dp11,#do11,#dt11,#dtp11,#ntt11,#ds11").hide();
					
				}
				else if(groupid === 13)
				{								
					$("#dp1,#do1,#dt1,#dtp1,#ntt1,#ds1").hide();
					$("#dp3,#do3,#dt3,#dtp3,#ntt3,#ds3").hide();
					$("#dp5,#do5,#dt5,#dtp5,#ntt5,#ds5").hide();
					$("#dp7,#do7,#dt7,#dtp7,#ntt7,#ds7").hide();
					$("#dp9,#do9,#dt9,#dtp9,#ntt9,#ds9,#dds9").hide();
				}
				else if(groupid === 21)
				{								
					$("#dp1,#do1,#dt1,#dtp1,#ntt1,#ds1").hide();
					$("#dp5,#do5,#dt5,#dtp5,#ntt5,#ds5").hide();
					$("#dp7,#do7,#dt7,#dtp7,#ntt7,#ds7").hide();
				}
			}
		<!--	Biology		-->	
			$("#p1,#o1,#t1,#tp1,#s1,#nt1").change(function(){
				
		//		$("#p13,#o13,#t13,#tp13,#s13,#nt13").val([ ]);
				$("#p3,#o3,#t3,#tp3,#s3,#nt3").val([ ]);
				$("#p5,#o5,#t5,#tp5,#s5,#nt5").val([ ]);
				$("#p7,#o7,#t7,#tp7,#s7,#nt7").val([ ]);
				$("#p9,#o9,#t9,#tp9,#s9,#nt9").val([ ]);
				$("#p11,#o11,#t11,#tp11,#s11,#nt11").val([ ]);
				$("#p12,#o12,#t12,#tp12,#s12,#nt12").val([ ]);
				nm = $(this).val();	
		//		alert(nm);
				sl = ($("option:selected", this).text());
		//		alert(sl);
				callFlexPaperDocViewer(sl);
				
				Check_OMR_sheet_And_response(nm,tab,sl);
				
			});
			  
		<!--	Math	-->	
			$("#p3,#o3,#t3,#tp3,#s3,#nt3").change(function(){
			
				$("#p1,#o1,#t1,#tp1,#s1,#nt1").val([ ]);
		//		$("#p13,#o13,#t13,#tp13,#s13,#nt13").val([ ]);
				$("#p5,#o5,#t5,#tp5,#s5,#nt5").val([ ]);
				$("#p7,#o7,#t7,#tp7,#s7,#nt7").val([ ]);
				$("#p9,#o9,#t9,#tp9,#s9,#nt9").val([ ]);
				$("#p11,#o11,#t11,#tp11,#s11,#nt11").val([ ]);
				$("#p12,#o12,#t12,#tp12,#s12,#nt12").val([ ]);
				nm = $(this).val();	
		//		alert(nm);
				sl = ($("option:selected", this).text());
		//		alert(sl);
				callFlexPaperDocViewer(sl);
				
				Check_OMR_sheet_And_response(nm,tab,sl);
				
			});
			  
		<!--	Physics	-->	
		  $("#p5,#o5,#t5,#tp5,#s5,#nt5").change(function(){
			
				$("#p1,#o1,#t1,#tp1,#s1,#nt1").val([ ]);
				$("#p3,#o3,#t3,#tp3,#s3,#nt3").val([ ]);
		//		$("#p13,#o13,#t13,#tp13,#s13,#nt13").val([ ]);
				$("#p7,#o7,#t7,#tp7,#s7,#nt7").val([ ]);
				$("#p9,#o9,#t9,#tp9,#s9,#nt9").val([ ]);
				$("#p11,#o11,#t11,#tp11,#s11,#nt11").val([ ]);
				$("#p12,#o12,#t12,#tp12,#s12,#nt12").val([ ]);
				nm = $(this).val();	
		//		alert(nm);
				sl = ($("option:selected", this).text());
		//		alert(sl);
				callFlexPaperDocViewer(sl);
				Check_OMR_sheet_And_response(nm,tab,sl);
				
			});
			  
		<!--	Chemistry	-->	
			$("#p7,#o7,#t7,#tp7,#s7,#nt7").change(function(){
			
				$("#p1,#o1,#t1,#tp1,#s1,#nt1").val([ ]);
				$("#p3,#o3,#t3,#tp3,#s3,#nt3").val([ ]);
				$("#p5,#o5,#t5,#tp5,#s5,#nt5").val([ ]);
		//		$("#p13,#o13,#t13,#tp13,#s13,#nt13").val([ ]);
				$("#p9,#o9,#t9,#tp9,#s9,#nt9").val([ ]);
				$("#p11,#o11,#t11,#tp11,#s11,#nt11").val([ ]);
				$("#p12,#o12,#t12,#tp12,#s12,#nt12").val([ ]);
				nm = $(this).val();	
		//		alert(nm);
				sl = ($("option:selected", this).text());
		//		alert(sl);
				callFlexPaperDocViewer(sl);
				
				Check_OMR_sheet_And_response(nm,tab,sl);
				
			});
			  
		<!--	Science	-->	
			$("#p9,#o9,#t9,#tp9,#s9,#nt9").change(function(){
			
				$("#p1,#o1,#t1,#tp1,#s1,#nt1").val([ ]);
				$("#p3,#o3,#t3,#tp3,#s3,#nt3").val([ ]);
				$("#p5,#o5,#t5,#tp5,#s5,#nt5").val([ ]);
				$("#p7,#o7,#t7,#tp7,#s7,#nt7").val([ ]);
		//		$("#p13,#o13,#t13,#tp13,#s13,#nt13").val([ ]);
				$("#p11,#o11,#t11,#tp11,#s11,#nt11").val([ ]);
				$("#p12,#o12,#t12,#tp12,#s12,#nt12").val([ ]);
				nm = $(this).val();	
		//		alert(nm);
				sl = ($("option:selected", this).text());
		//		alert(sl);
				callFlexPaperDocViewer(sl);
				
				Check_OMR_sheet_And_response(nm,tab,sl);
				
			});
			  
	<!--	English	-->	
			$("#p11,#o11,#t11,#tp11,#s11,#nt11").change(function(){
			
				$("#p1,#o1,#t1,#tp1,#s1,#nt1").val([ ]);
				$("#p3,#o3,#t3,#tp3,#s3,#nt3").val([ ]);
				$("#p5,#o5,#t5,#tp5,#s5,#nt5").val([ ]);
				$("#p7,#o7,#t7,#tp7,#s7,#nt7").val([ ]);
				$("#p9,#o9,#t9,#tp9,#s9,#nt9").val([ ]);
		//		$("#p13,#o13,#t13,#tp13,#s13,#nt13").val([ ]);
				$("#p12,#o12,#t12,#tp12,#s12,#nt12").val([ ]);
				nm = $(this).val();	
		//		alert(nm);
				sl = ($("option:selected", this).text());
		//		alert(sl);
				callFlexPaperDocViewer(sl);
				
				Check_OMR_sheet_And_response(nm,tab,sl);
				
			});
			
	<!--	Social Study	-->	
			$("#p12,#o12,#t12,#tp12,#s12,#nt12").change(function(){
			
				$("#p1,#o1,#t1,#tp1,#s1,#nt1").val([ ]);
				$("#p3,#o3,#t3,#tp3,#s3,#nt3").val([ ]);
				$("#p5,#o5,#t5,#tp5,#s5,#nt5").val([ ]);
				$("#p7,#o7,#t7,#tp7,#s7,#nt7").val([ ]);
				$("#p9,#o9,#t9,#tp9,#s9,#nt9").val([ ]);
		//		$("#p13,#o13,#t13,#tp13,#s13,#nt13").val([ ]);
				$("#p11,#o11,#t11,#tp11,#s11,#nt11").val([ ]);
				nm = $(this).val();	
		//		alert(nm);
				sl = ($("option:selected", this).text());
		//		alert(sl);
				callFlexPaperDocViewer(sl);
				
				Check_OMR_sheet_And_response(nm,tab,sl);
				
			});
			  
	<!--	Combined	-->	
			$("#p13,#o13,#t13,#tp13,#s13,#nt13").click(function(){
			
				$("#p1,#o1,#t1,#tp1,#s1,#nt1").val([ ]);
				$("#p3,#o3,#t3,#tp3,#s3,#nt3").val([ ]);
				$("#p5,#o5,#t5,#tp5,#s5,#nt5").val([ ]);
				$("#p7,#o7,#t7,#tp7,#s7,#nt7").val([ ]);
				$("#p9,#o9,#t9,#tp9,#s9,#nt9").val([ ]);
				$("#p11,#o11,#t11,#tp11,#s11,#nt11").val([ ]);
				$("#p12,#o12,#t12,#tp12,#s12,#nt12").val([ ]);
	
				nm = $(this).val();	
		//		alert(nm);
				sl = ($("option:selected", this).text());
		//		alert(sl);
				callFlexPaperDocViewer(sl);
				
				Check_OMR_sheet_And_response(nm,tab,sl);
				
			});
			
			
<!-- GET Contenet -->
			function getContent(filename, selectboxid)
			{
				$.ajax({
					url: filename,
					type: 'GET',
					dataType: 'html',
					
					success: function(data, textStatus, xhr) {
						var strtemp = "$('#" + selectboxid + "').html(data)";
						eval(strtemp);
						//alert(data);
					},
				});									
			}
	<!--Solution	-->
			$("#s14,#p14,#o14,#t14,#tp14").click(function(){
				nxt = $(this).val();
		//		alert(nxt);
				callFlexPaperDocViewer(nxt);
			});
	<!-- ba -->
			$("#s1,#s3,#s5,#s7,#s9,#s11,#s12,#s13").change(function()
				{	
					
					
					$("#s14").val() = "";
			/*		var filename = "";
					filename = "query/query9.php?dt="+nm;
					getContent(filename,"s14");
			*/
				});
	<!-- pa -->
			$("#p1,#p3,#p5,#p7,#p9,#p11,#p12,#p13").change(function()
				{	
					$("#p14").val() = "";

		/*
					var filename = "";
					filename = "query/query9.php?dt="+nm;
					getContent(filename,"p14");
			*/
				});
	<!-- other -->
			$("#t1,#t3,#t5,#t7,#t9,#t11,#t12,#t13").change(function()
			{	
				$("#t14").val() = "";

		/*		
				var filename = "";
				filename = "query/query9.php?dt="+nm;
				getContent(filename,"t14");
		*/
			});
	<!-- objective -->
			$("#o1,#o3,#o5,#o7,#o9,#o11,#o12,#o13").click(function()
			{	
				$("#o14").val() = "";

		/*
				var filename = "";
				filename = "query/query9.php?dt="+nm;
				getContent(filename,"o14");
		*/
			});
	<!-- subjective -->
			$("#tp1,#tp3,#tp5,#tp7,#tp9,#tp11,#tp12,#tp13").change(function()
			{	
				$("#tp14").val() = "";

		/*		
				var filename = "";
				filename = "query/query10.php?dt="+nm;
				// alert(filename);
				getContent(filename,"tp14");
		*/
			});
	<!-- notes -->
			$("#nt1,#nt3,#nt5,#nt7,#nt9,#nt11,#nt12,#nt13").change(function()
				{	
					$("#nt14").val() = "";

			/*		
					var filename = "";
					filename = "query/query9.php?dt="+nm;
					//alert(filename);
					getContent(filename,"nt14");
			*/
				});
		<!--  Batch Assignment  -->
			$('#Assign').click(function()
			{	
				$("#Show_OMR_Div").hide();
				$("#OMR_result").hide();
				show_sdf_tools_plan();
				
				tab = 1001;

				filename = "query/query.php?dt=1";
				getContent(filename,"s1");
				filename = "query/query2.php?dt=1";
				getContent(filename, "s3");
				filename = "query/query3.php?dt=1";
				getContent(filename, "s5");
				filename = "query/query4.php?dt=1";
				getContent(filename, "s7");
				filename = "query/query5.php?dt=1";
				getContent(filename, "s9");
				filename = "query/query6.php?dt=1";
				getContent(filename, "s11");
				filename = "query/query8.php?dt=1";
				getContent(filename, "s12");
				filename = "query/query7.php?dt=1";
				getContent(filename, "s13");
				filename = "query/query9.php?dt=a";
				getContent(filename,"s14");
			});
			
			<!-- this is Personal anchor tag -->

			$('#persnl').click(function()
			{	
				$("#Show_OMR_Div").hide();
				$("#OMR_result").hide();
				show_sdf_tools_plan();
				
				tab = 1002;

				filename = "query/query.php?dt2=2";
				getContent(filename,"p1");
				filename = "query/query2.php?dt2=2";
				getContent(filename, "p3");
				filename = "query/query3.php?dt2=2";
				getContent(filename, "p5");
				filename = "query/query4.php?dt2=2";
				getContent(filename, "p7");
				filename = "query/query5.php?dt2=2";
				getContent(filename, "p9");
				filename = "query/query6.php?dt2=2";
				getContent(filename, "p11");
				filename = "query/query8.php?dt=2";
				getContent(filename, "s12");
				filename = "query/query7.php?dt2=2";
				getContent(filename, "p13");
				filename = "query/query9.php?dt=a";
				getContent(filename,"p14");
					
			});
			<!-- this is other anchor tag -->
			$('#other').click(function()
			{	
				$("#Show_OMR_Div").hide();
				$("#OMR_result").hide();
				show_sdf_tools_plan();
				
				tab = 1003;

				filename = "query/query.php?dt4=4";
				getContent(filename,"t1");
				filename = "query/query2.php?dt4=4";
				getContent(filename, "t3");
				filename = "query/query3.php?dt4=4";
				getContent(filename, "t5");
				filename = "query/query4.php?dt4=4";
				getContent(filename, "t7");
				filename = "query/query5.php?dt4=4";
				getContent(filename, "t9");
				filename = "query/query6.php?dt4=4";
				getContent(filename, "t11");
				filename = "query/query8.php?dt4=4";
				getContent(filename, "s12");
				filename = "query/query7.php?dt4=4";
				getContent(filename, "t13");
				filename = "query/query9.php?dt=a";
				getContent(filename,"t14");
					
			});
	<!-- this is objective paper test anchor tag -->

			$('#obj').click(function()
			{	
				$("#Show_OMR_Div").hide();
				$("#OMR_result").hide();
				show_sdf_tools_plan();
				
				tab = 1004;

				filename = "query/query.php?dt3=25";
				getContent(filename,"o1");
				filename = "query/query2.php?dt3=25";
				getContent(filename, "o3");
				filename = "query/query3.php?dt3=25";
				getContent(filename, "o5");
				filename = "query/query4.php?dt3=25";
				getContent(filename, "o7");
				filename = "query/query5.php?dt3=25";
				getContent(filename, "o9");
				filename = "query/query6.php?dt3=25";
				getContent(filename, "o11");
				filename = "query/query8.php?dt3=25";
				getContent(filename, "s12");
				filename = "query/query7.php?dt3=25";
				getContent(filename, "o13");
				filename = "query/query9.php?dt=a";
				getContent(filename,"o14");
					
			});
			

<!-- this is subjective paper test anchor tag -->
			$('#sub').click(function()
			{	
				$("#Show_OMR_Div").hide();
				$("#OMR_result").hide();
				show_sdf_tools_plan();
				
				tab = 1005;

				filename = "query/query.php?dt5=26";
				getContent(filename,"tp1");
				filename = "query/query2.php?dt5=26";
				getContent(filename, "tp3");
				filename = "query/query3.php?dt5=26";
				getContent(filename, "tp5");
				filename = "query/query4.php?dt5=26";
				getContent(filename, "tp7");
				filename = "query/query5.php?dt5=26";
				getContent(filename, "tp9");
				filename = "query/query6.php?dt5=26";
				getContent(filename, "tp11");
				filename = "query/query8.php?dt5=26";
				getContent(filename, "s12");
				filename = "query/query7.php?dt5=26";
				getContent(filename, "tp13");
				filename = "query/query10.php?dt=a";
				getContent(filename,"tp14");
	
			});
			<!-- this is Notes anchor tag -->
			$('#not').click(function()
			{	
				$("#Show_OMR_Div").hide();
				$("#OMR_result").hide();
				//alert("note");
				show_sdf_tools_plan();
				
				tab = 1006;

				filename = "query/query.php?dt6=8";
				getContent(filename,"nt1");
				filename = "query/query2.php?dt6=8";
				getContent(filename, "nt3");
				filename = "query/query3.php?dt6=8";
				getContent(filename, "nt5");
				filename = "query/query4.php?dt6=8";
				getContent(filename, "nt7");
				filename = "query/query5.php?dt6=8";
				getContent(filename, "nt9");
				filename = "query/query6.php?dt6=8";
				getContent(filename, "nt11");
				filename = "query/query8.php?dt6=8";
				getContent(filename, "nt12");
				filename = "query/query7.php?dt6=8";
				getContent(filename, "nt13");
				filename = "query/query9.php?dt=a";
				getContent(filename,"nt14");
			});
			var chap_id = "";
			var top_id = "";
			var add_name="";
			$( "#chap1, #chap2" ).selectable({
				selected: function(event, ui) {
					chap_id = ( $(ui.selected).attr('id') );
					var url = "";
					url = "query/2.php?chp_id="+chap_id+"&uid="+u_id+"&bt_id="+bt_id+"&type_lect="+tl;
					//alert(url);
					getContent(url,"top1");
					url = "query/2_2.php?chp_id="+chap_id+"&uid="+u_id+"&bt_id="+bt_id+"&type_lect="+tl;
					getContent(url,"top2");
					
					url = "query/query3_3_4.php?chp_id="+chap_id+"&uid="+u_id+"&bta="+bt_id+"&type_lect="+tl;
				
					getContent(url,"top3");
					
					$("#additional_topic_cover").show();
					
				}
			});
			
			$( "#top1" ).sortable({
				connectWith: "ul",
				update: function(evenet, ui ) {
					reloadChapterLists();
					//chap_chart();
					//sub_chart();
				}
			});
			$( "#top2" ).sortable({
				connectWith: "ul",
				receive: function( event, ui ) {
					top_id  = ($(ui.item).attr("id"));
					//alert("top id is : : : "+top_id);
					filename = "query/4.php?dt1="+u_id+"&dt2="+sub_id+"&dt3="+br_id+"&dt4="+bt_id+"&dt5="+chap_id+"&dt6="+top_id+"&type_lect="+tl;
					//alert(filename);
					getInsert(filename);
				},
				remove: function(evenet, ui ) {
					top_id  = ($(ui.item).attr("id"));
					filename = "query/5.php?dt9="+top_id;
					//alert("delete Data : "+filename);
					getDelete(filename);
					
				},
				update: function(evenet, ui ) {
					reloadChapterLists();
					//chap_chart();
					//sub_chart();
				}
				
			});
				
				
			
			function reloadChapterLists() {
				filename = "query/1.php?dt3="+sub_id+"&uid="+u_id+"&bt_id="+bt_id+"&type_lect="+tl;
				//alert(filename);
				$.ajax({
					url: filename,
					type: 'GET',
					dataType: 'html',
					success: function(data, textStatus, xhr) {
						var strtemp = $('#chap1').html(data);
						eval(strtemp);
					}
				});	
				filename = "query/1_1.php?dt3="+sub_id+"&uid="+u_id+"&bt_id="+bt_id+"&type_lect="+tl;
				$.ajax({
					url: filename,
					type: 'GET',
					dataType: 'html',
					success: function(data, textStatus, xhr) {
						var strtemp = $('#chap2').html(data);
						eval(strtemp);
					}
				});
			}
			function getInsert(filename)
			{
				$.ajax({
					url: filename,
					type: 'GET',
					dataType: 'html',
					
					success: function(data, textStatus, xhr) {
						//alert(data);
					},
				});									
			}
			function getDelete(filename)
			{
				$.ajax({
					url: filename,
					type: 'GET',
					dataType: 'html',
					
					success: function(data, textStatus, xhr) {
						//alert("success"+data);
					},
				});									
			}
			
			$( "#top1, #top2, #top3" ).disableSelection();
			
			$("#subg").click(function(){
				$("#chap1, #chap2, #top1, #top2, #top3").empty();
				sub_id = $("#subg").val();
			//	alert(sub_id); lect_type
				filename = "query/viewLectType.php";
				$.ajax({
					url: filename,
					type: 'GET',
					dataType: 'html',
					
					success: function(data, textStatus, xhr) {
						 $('#lect_type').html(data);
					},
				});	
				$("#chart").hide();
				$("#additional_topic_cover").hide();
				$("#lect_type").show();
				$("#llt").show();
			});
			
			$("#lect_type").hide();
			$("#llt").hide();
			
			$("#lect_type").click(function(){
				$("#chap1, #chap2, #top1, #top2, #top3").empty();
				tl = $("#lect_type").val();
			//	alert(tl);
				filename = "query/1.php?dt3="+sub_id+"&uid="+u_id+"&bt_id="+bt_id+"&type_lect="+tl;
			//	alert(filename);
				$.ajax({
					url: filename,
					type: 'GET',
					dataType: 'html',
					success: function(data, textStatus, xhr) {
						var strtemp = $('#chap1').html(data);
						eval(strtemp);
					}
				});
				reloadChapterLists();
				$("#additional_topic_cover").hide();
			});
			
			$("#add_topic").click(function(){
				//	alert("hello");
					// post  uid,add_top_name,chap_id,wb_id
					add_name = $("#atcvr").val();
					//alert("topic"+add_name);
					filename = "query/insert_add_topic.php?name="+add_name+"&uid="+u_id+"&bta="+bt_id+"&chap_id="+chap_id+"&type_lect="+tl;
					//alert("query Run : "+filename);
					getInsert(filename);
					$("#atcvr").val('');
					
					url = "query/query3_3_4.php?chp_id="+chap_id+"&uid="+u_id+"&bta="+bt_id+"&type_lect="+tl;
					//alert("Data inserted");
					
					getContent(url,"top3");
					
				});
				
			$("#additional_topic_cover").hide();
			
			$("#cp").click(function(){
				//alert("alert");
				$("#doc34").hide();
				$("#plan").hide();
				$("#Show_OMR_Div").hide();
				$("#OMR_result").hide();
				
			});
			$( "#datepicker" ).datepicker({
					dateFormat: "yy-mm-dd",
					altField: "#alternate",
					altFormat: "DD, d MM, yy",
					onSelect: function() { 
						//alert("Date Selected");	
						datepickerVal = $("#datepicker").val();
						//alert(datepickerVal);		
					}
			});
			
			$("#chart").hide();
			
			$("#chart").click(function()
			{						
					var url = "viewChart.php?sub="+sub_id+"&bta="+bt_id+"&tl="+tl+"&uid="+u_id;    
					//alert(url);	
					window.open(url, 'Evolution of Course Progress', 'height=800,width=1000,left=10,top=10,resizable=yes,scrollbars=yes,toolbar=no,menubar=no,location=no,directories=no,status=yes');
					return false;
					
			});
			
			
			// Checking for OMR sheet and give test or not
			function Check_OMR_sheet_And_response(material_id_get,tab,material_name)
			{
			//	setTimeout(function(){
				
				filename = "query/check_omr_response_table.php?material_id="+material_id_get;
			//	alert(filename);
				$.ajax({
					url: filename,
					type: 'GET',
					dataType: 'html',
					success: function(data, textStatus, xhr) {
						ck_omr = data;
						
					}
				});
			//	alert(material_name);
				//alert(ck_omr);
				
					if(ck_omr == "Insert_Data")
					{
						$("#Show_OMR_Div").show();
						$("#OMR_result").hide();
						filename = "query/OMR_Sheet_Fill.php?material_id="+material_id_get;
						getContent(filename,"dv");
						
					}
					else
					{	
						//  data_available
						$("#Show_OMR_Div").hide();
						$("#OMR_result").show();
						filename = "query/omr_result_check.php?material_id="+material_id_get;
					//	alert(filename);
						$.ajax({
							url: filename,
							type: 'GET',
							dataType: 'html',
							success: function(data, textStatus, xhr) {
								var strtemp = $('#OMR_result_declare').html(data);
								
								eval(strtemp);
							}
							
						});
						filename = "query/query9.php?dt="+material_id_get;
				//		alert("filename.."+filename);
						var filename2 = "query/query10.php?dt="+material_id_get;
				//		alert("filename2.."+filename2);
				//		alert("new tab value..........."+tab);
						if(tab == 1001)
						{
							getContent(filename,"s14");
						}
						else if(tab == 1002)
						{
							getContent(filename,"p14");
						}
						else if(tab == 1003)
						{
							getContent(filename,"t14");
						}
						else if(tab == 1004)
						{
							getContent(filename,"o14");
						}
						else if(tab == 1005)
						{
							getContent(filename2,"tp14");
						}
						else if(tab == 1006)
						{
							getContent(filename,"nt14");
						}
					}
			//	}, 2000);
				
			
			}
			
			$("#OMR_answer_submit").click(function(){
			//	alert("tau");
				check_student_id = "";
				var idArray2 = [];
				$("#student_come input:checkbox").each(function() {
					if ($(this).is(":checked"))
					{
						idArray2.push(this.id);
					}
				});
				check_student_id = idArray2;
				if(check_student_id == "")
				{
					alert("Please give proper test");
				}
				else
				{
					
					
					var nw = ""+check_student_id+"";
					var array = nw.split(',');
					for (var i in array){
						if(i >= 0)
						{
							var array2 = array[i].split('-');
						//	alert("array"+array2);
							for (var j in array2){
							//	alert(array2[j]);
								var gh=array2[0];
								var gh2 = array2[1];	
							}
						//	alert(gh+"value"+gh2);
							filename = "query/insert_OMR_response.php?material_id="+nm+"&qno="+gh+"&response="+gh2;
						//	alert(filename);
							$.ajax({
								url: filename,
								type: 'GET',
								dataType: 'html',
								success: function(data, textStatus, xhr) {
								//	alert(data);
								}
							});
							
						}
						else
						{
							alert("Insert data");
						}
					}
					
					filename = "query/omr_result_check.php?material_id="+nm;
				//	alert(filename);
					$.ajax({
						url: filename,
						type: 'GET',
						dataType: 'html',
						success: function(data, textStatus, xhr) {
							var strtemp = $('#OMR_result_declare').html(data);
							$("#OMR_result").show();
							eval(strtemp);
						}
					});
					
				//	alert("call tab..."+tab);
					
					filename = "query/query9.php?dt="+nm;
					var filename2 = "query/query10.php?dt="+nm;
					if(tab == 1001)
					{
						getContent(filename,"s14");
					}
					else if(tab == 1002)
					{
						getContent(filename,"p14");
					}
					else if(tab == 1003)
					{
						getContent(filename,"t14");
					}
					else if(tab == 1004)
					{
						getContent(filename,"o14");
					}
					else if(tab == 1005)
					{
						getContent(filename2,"tp14");
					}
					else if(tab == 1006)
					{
						getContent(filename,"nt14");
					}
					
				}
				
			//	alert("data::"+check_student_id);
				
			});
			
		});
		</script> 
		 <script>
			$(function() {
			$( "#tabs" ).tabs().addClass( "ui-tabs-vertical ui-helper-clearfix" );
			$( "#tabs li" ).removeClass( "ui-corner-top" ).addClass( "ui-corner-left" );
			});
		</script>		
	</head>
	<body>
		<?php 
			
			$result=mysql_query("SELECT NAME AS group_name FROM `group` WHERE id=".$s3);
			$result1=mysql_query("Select name as batch_name from batch where id=".$s4);
			$result2=mysql_query("SELECT NAME as standard_name FROM standard WHERE id=".$s2);
			
			$row=mysql_fetch_array($result);
			if($row)
			{
				$grp1 = $row['group_name'];
			}
		
			$row1=mysql_fetch_array($result1);
			if($row1)
			{
				$btch1 = $row1['batch_name'];
			}	
			$row2=mysql_fetch_array($result2);
			if($row2)
			{
				$std2 = $row2['standard_name'];
			}	
		?>
		
		<?php require 'header.php'; ?>

			<div><h3><b>
				Welcome <?php echo $u5 ?> !
				</b></h3>
			</div>
			
			<div>
				<?php echo  "Student ID : ".$s1;
				echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
				echo "Student Standard: ".$std2. "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Group : ".$grp1. "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Batch Name : ".$btch1;
			
				?>
				
			</div>
		<!--	<div id="colorstrip" style="font-size: 16px; color: black">àª¡àª¾àª¯àª—à«àª¨à«‹àª¸à«àªŸàª¿àª• àª°àª¿àªªà«‹àª°à«àªŸ àª…àª¨à«‡ àªªàª°à«àª¸àª¨àª²àª¾àª‡àªà«àª¡ àª…àª¸àª¾àªˆàª¨à«àªŸàª®à«‡àª¨à«àªŸ Edutech India àª¨àª¾àª‚ àª°à«‡àª—à«àª²àª° àªŸà«‡àª¸à«àªŸ àª¸àª¿àª°à«€àª àª¨àª¾àª‚ àªµàª¿àª¦à«àª¯àª¾àª°à«àª¥àª¿àª¯à«‹ àª®àª¾àªŸà«‡ àª‰àªªàª²àª¬à«àª§ àª›à«‡</div>-->
			<div id="tabs" style="height: 560px;">
				<ul>
					<li><a href="#tabs-1" id="Assign" style="width:105px;"><font size="1"><b>Batch Assignments</b></font></a></li>					
					<li><a href="#tabs-2" id="persnl"style="width:150px;"><font size="1"><b>Personalised Assignments</b></font></a></li>					
					<li><a href="#tabs-4" id="other" style="width:117px;"><font size="1"><b>Other School Papers</b></font></a></li>
					<li><a href="#tabs-3" id="obj" style="width:183px;"><font size="1"><b>Previous Test Papers-Objective</b></font></a></li>
					<li><a href="#tabs-5" id="sub" style="width:187px;"><font size="1"><b>Previous Test Papers-Subjective</b></font></a></li>
					<li><a href="#tabs-6" id="not" style="width:40px;"><font size="1"><b>Notes</b></font></a></li>
					
					<li><a href="#tabs-7" id="cp" style="width:100px;"><font size="1"><b>Course Progress</b></font></a></li>
					
				</ul>
				<div class="tabs-spacer"></div>
					<div id="tabs-1" name="ba">

						<div id="ds1">
							<label>Biology Material</label>
							<br />
							<select name="data" size="4" id="s1" style="width: 200px; color:#777777"  >
							</select>
						</div>
						
						<div id="ds3">
							<br />
							<label>Math Material</label>
							<br />
							<select name="data3" size="4" id="s3" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="ds5">
							<br />
							<label>Physics Material</label>
							<br />
							<select name="data5" size="4" id="s5" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="ds7">
							<br />
							<label>Chemistry Material</label>
							<br />
							<select name="data7" size="4" id="s7" style="width: 200px; color:#777777" >
							</select>					
						</div>
						<div id="ds9">
							<br />
							<label>Science Material</label>
							<br />
							<select name="data9" size="4" id="s9" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="ds11">
							<br />
							<label>English Material</label>
							<br />
							<select name="data11" size="4" id="s11" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="ds12">
							<br />
							<label>Social Study Material</label>
							<br />
							<select name="data12" size="4" id="s12" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="ds13">
							<br />
							<label>Combined Material</label>
							<br />
							<select name="data13" size="4" id="s13" style="width: 200px; color:#777777" >
							</select>
						</div>
					
						<div id="ds14">
							<br />
							<label>Solution/Report</label>
							<br />
							<select name="data13" size="4" id="s14" style="width: 200px; color:#777777" >
							</select>
						</div>
					
					</div>

					<div id="tabs-2" name="pa">

						<div id="dp1">
							<label>Biology Material</label>
							<br />
							<select name="data" size="4" id="p1" style="width: 200px; color:#777777"  >
							</select>
						</div>
						
						<div id="dp3">
							<br />
							<label>Math Material</label>
							<br />
							<select name="data3" size="4" id="p3" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dp5">	
							<br />
							<label>Physics Material</label>
							<br />
							<select name="data5" size="4" id="p5" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dp7">	
							<br />
							<label>Chemistry Material</label>
							<br />
							<select name="data7" size="4" id="p7" style="width: 200px; color:#777777" >
							</select>					
						</div>
						
						<div id="dp9">
							<br />
							<label>Science Material</label>
							<br />
							<select name="data9" size="4" id="p9" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dp11">
							<br />
							<label>English Material</label>
							<br />
							<select name="data11" size="4" id="p11" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dp12">
							<br />
							<label>Social Study Material</label>
							<br />
							<select name="data12" size="4" id="p12" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dp13">
							<br />
							<label>Combined Material</label>
							<br />
							<select name="data13" size="4" id="p13" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dp14">
							<br />
							<label>Solution/Report</label>
							<br />
							<select name="data13" size="4" id="p14" style="width: 200px; color:#777777" >
							</select>
						</div>
						
					</div>

					<div id="tabs-4" name="other">
						<div id="dt1">
							<label>Biology Material</label>
							<br />
							<select name="data" size="4" id="t1" style="width: 200px; color:#777777"  >
							</select>
						</div>
						
						<div id="dt3">
							<br />
							<label>Math Material</label>
							<br />
							<select name="data3" size="4" id="t3" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dt5">	
							<br />
							<label>Physics Material</label>
							<br />
							<select name="data5" size="4" id="t5" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dt7">	
							<br />
							<label>Chemistry Material</label>
							<br />
							<select name="data7" size="4" id="t7" style="width: 200px; color:#777777" >
							</select>					
						</div>
						
						<div id="dt9">
							<br />
							<label>Science Material</label>
							<br />
							<select name="data9" size="4" id="t9" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dt11">
							<br />
							<label>English Material</label>
							<br />
							<select name="data11" size="4" id="t11" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dt12">
							<br />
							<label>Social Study Material</label>
							<br />
							<select name="data12" size="4" id="t12" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dt13">
							<br />
							<label>Combined Material</label>
							<br />
							<select name="data13" size="4" id="t13" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dt14">
							<br />
							<label>Solution/Report</label>
							<br />
							<select name="data13" size="4" id="t14" style="width: 200px; color:#777777" >
							</select>
						</div>
					</div>
					<div id="tabs-3" name="objective">
						<div id="do1">
							<label>Biology Material</label>
							<br />
							<select name="data" size="4" id="o1" style="width: 200px; color:#777777"  >
							</select>
						</div>
						<div id="do3">
							<br />
							<label>Math Material</label>
							<br />
							<select name="data3" size="4" id="o3" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="do5">
							<br />
							<label>Physics Material</label>
							<br />
							<select name="data5" size="4" id="o5" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="do7">	
							<br />
							<label>Chemistry Material</label>
							<br />
							<select name="data7" size="4" id="o7" style="width: 200px; color:#777777" >
							</select>					
						</div>
						
						<div id="do9">
							<br />
							<label>Science Material</label>
							<br />
							<select name="data9" size="4" id="o9" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="do11">
							<br />
							<label>English Material</label>
							<br />
							<select name="data11" size="4" id="o11" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="do12">
							<br />
							<label>Social Study Material</label>
							<br />
							<select name="data12" size="4" id="o12" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="do13">
							<br />
							<label>Mock Tests</label>
							<br />
							<select name="data13" size="4" id="o13" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="do14">
							<br />
							<label>Solution/Report</label>
							<br />
							<select name="data13" size="4" id="o14" style="width: 200px; color:#777777" >
							</select>
						</div>
						
					</div>
					
					<div id="tabs-5" name="subjective">
						<div id="dtp1">
							<label>Biology Material</label>
							<br />
							<select name="data" size="4" id="tp1" style="width: 200px; color:#777777"  >
							</select>
						</div>
						
						<div id="dtp3">
							<br />
							<label>Math Material</label>
							<br />
							<select name="data3" size="4" id="tp3" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dtp5">	
							<br />
							<label>Physics Material</label>
							<br />
							<select name="data5" size="4" id="tp5" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dtp7">	
							<br />
							<label>Chemistry Material</label>
							<br />
							<select name="data7" size="4" id="tp7" style="width: 200px; color:#777777" >
							</select>					
						</div>
						
						<div id="dtp9">
							<br />
							<label>Science Material</label>
							<br />
							<select name="data9" size="4" id="tp9" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dtp11">
							<br />
							<label>English Material</label>
							<br />
							<select name="data11" size="4" id="tp11" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dtp12">
							<br />
							<label>Social Study Material</label>
							<br />
							<select name="data12" size="4" id="tp12" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dtp13">
							<br />
							<label>Combined Material</label>
							<br />
							<select name="data13" size="4" id="tp13" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="dtp14">
							<br />
							<label>Solution/Report</label>
							<br />
							<select name="data13" size="4" id="tp14" style="width: 200px; color:#777777" >
							</select>
						</div>
					</div>
					<div id="tabs-6" name="notes">
						<div id="ntt1">
							<label>Biology Material</label>
							<br />
							<select name="data" size="4" id="nt1" style="width: 200px; color:#777777"  >
							</select>
						</div>
						
						<div id="ntt3">
							<br />
							<label>Math Material</label>
							<br />
							<select name="data3" size="4" id="nt3" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="ntt5">	
							<br />
							<label>Physics Material</label>
							<br />
							<select name="data5" size="4" id="nt5" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="ntt7">	
							<br />
							<label>Chemistry Material</label>
							<br />
							<select name="data7" size="4" id="nt7" style="width: 200px; color:#777777" >
							</select>					
						</div>
						
						<div id="ntt9">
							<br />
							<label>Science Material</label>
							<br />
							<select name="data9" size="4" id="nt9" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="ntt11">
							<br />
							<label>English Material</label>
							<br />
							<select name="data11" size="4" id="nt11" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="ntt12">
							<br />
							<label>Social Study Material</label>
							<br />
							<select name="data12" size="4" id="nt12" style="width: 200px; color:#777777" >
							</select>
						</div>
						
						<div id="ntt13">
							<br />
							<label>Combined Material</label>
							<br />
							<select name="data13" size="4" id="nt13" style="width: 200px; color:#777777" >
							</select>
						</div>
					</div>
					
					<div id="tabs-7" name="course_progress">
							<div>
								<!--<label><b>Select Date : </b></label>
								
									
										<input type="text" id="datepicker" value="<?php echo $today ?>" />
										<input type="text" id="alternate" size="30" value="<?php echo $today2 ?>" />
								-->
										<input type="BUTTON" name="chart" class="classname" value="View Graphically Course Progress" id="chart">
									</br>
									</br>
									
									<label><b>Select Subject</b></label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label id="llt"><b>Select Lecture Type</b></label>
									</br></br>
									<label class="custom-select">
									<select name="subject_g" id="subg" size="5" style="width:150px;height:120px;font-size:12px;">
										<?php
											$result=mysql_query("SELECT g.group_id,s.name,g.sub_id FROM SUBJECT s,group_subject_mapping g WHERE s.id=g.sub_id AND g.group_id=".$s3." AND s.id!=20");
											while($row=mysql_fetch_array($result))
											{
												echo "<option value=$row[2]>$row[1]</option>";
											}
										?>
									</select> 
									</label>
									<label class="custom-select">
										<select name="lect_type" id="lect_type" size="5" style="width:200px;height:120px;font-size:12px;">
										</select> 
									</label>
									
							</div>
							<br/>
						<table style="width:1000px;">
							<tr>
								<th>Chapter</th>
								<th>Topic</th>
							</tr>
							<tr>
							<td style="width: 37%;">
								<table style="width:100%;">
									<tr>
										<th><b>Chapter List</b></th>
										
										<th><b>Chapter Covered</b></th>
									</tr>
									<tr>
										<td>
											<ul id="chap1" style="height: 202px; overflow: auto;"></ul>
										</td>
										
										<td>
											<ul id="chap2" style="height: 202px; overflow: auto;"></ul>
										</td>
									</tr>
								</table>
							</td>
							<td style="width: 60%;">
									<table style="width:100%;">
									<tr>
										<th><b>Topic List</b></th>
										
										<th><b>Topic Covered</b></th>
										
										<th><b>Additional Topic</b></th>
									</tr>
									<tr>
										<td>
											<ul id="top1" style="height: 202px; overflow: auto;"></ul>
										</td>
										
										<td>
											<ul id="top2" style="height: 202px; overflow: auto;"></ul>
										</td>
										<td>
											<ul id="top3" class="" style="height: 202px; overflow: auto;">
											</ul>
										</td>
									</tr>
								</table>
							</td>
							</tr>
							<tr>
								<td>
								</td>
								<td>
									<div id="additional_topic_cover">
										&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
										&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
										&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
										&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
										&nbsp;&nbsp;&nbsp;&nbsp;
										<label><b>Additional Topic Covered: </b></label>
										<input type="text" id="atcvr" value="" placeholder="Additional Topic " style="width:250px;" />
										<input type="button" id="add_topic" class="classname" value="Add" />
									</div>
								</td>
							</tr>
						</table>
					</div>
			</div>	
				<div>
					<br />
				</div>
						
			<div id="doc34" style="position:absolute;left:250px;top:127px;">
				<div id="documentViewer" class="flexpaper_viewer" style="width:750px;height:500px"></div>

				<script type="text/javascript">
					function getDocumentUrl(document){
						//alert(document);
						//alert("services/view.php?doc={doc}&format={format}&page={page}");
						return "services/view.php?doc={doc}&format={format}&page={page}".replace("{doc}",document);
					}

					function getDocQueryServiceUrl(document){
						return "services/swfsize.php?doc={doc}&page={page}".replace("{doc}",document);
					}
					
					var startDocument = "<?php if(isset($_GET["doc"])){echo $_GET["doc"];}else{?>Paper2.pdf<?php } ?>";

					$('#documentViewer').FlexPaperViewer(
					 {
					 config : {

							 DOC : escape(getDocumentUrl(startDocument)),
							 Scale : 0.6,
							 ZoomTransition : 'easeOut',
							 ZoomTime : 0.5,
							 ZoomInterval : 0.2,
							 FitPageOnLoad : false,
							 FitWidthOnLoad : true,
							 FullScreenAsMaxWindow : false,
							 ProgressiveLoading : false,
							 MinZoomSize : 0.2,
							 MaxZoomSize : 5,
							 SearchMatchAll : false,
							 InitViewMode : 'Portrait',
							 RenderingOrder : 'flash,html',

							 ViewModeToolsVisible : true,
							 ZoomToolsVisible : true,
							 NavToolsVisible : true,
							 CursorToolsVisible : true,
							 SearchToolsVisible : true,

							 DocSizeQueryService : 'services/swfsize.php?doc=' + startDocument,
							 jsDirectory : 'js/',
							 localeDirectory : 'locale/',

							 JSONDataType : 'jsonp',
							 key : '',

							 localeChain: 'en_US'

							 }}
					);
					
					//callFlexPaperDocViewer("Paper.pdf");
					
					function callFlexPaperDocViewer(startDocument1){
						//alert(startDocument1);
					
							$('#documentViewer').FlexPaperViewer(
					 { config : {

							 DOC : escape(getDocumentUrl(startDocument1)),
							 Scale : 0.6,
							 ZoomTransition : 'easeOut',
							 ZoomTime : 0.5,
							 ZoomInterval : 0.2,
							 FitPageOnLoad : false,
							 FitWidthOnLoad : true,
							 FullScreenAsMaxWindow : false,
							 ProgressiveLoading : false,
							 MinZoomSize : 0.2,
							 MaxZoomSize : 5,
							 SearchMatchAll : false,
							 InitViewMode : 'Portrait',
							 RenderingOrder : 'flash,html',

							 ViewModeToolsVisible : true,
							 ZoomToolsVisible : true,
							 NavToolsVisible : true,
							 CursorToolsVisible : true,
							 SearchToolsVisible : true,

							 DocSizeQueryService : 'services/swfsize.php?doc=' + startDocument1,
							 jsDirectory : 'js/',
							 localeDirectory : 'locale/',

							 JSONDataType : 'jsonp',
							 key : '',

							 localeChain: 'en_US'

							 }}
					);
					}
				</script>
			</div>
			
			<div id="plan" style="position:absolute;left:1010px;top:130px;">
				<table>
					<tr>
						<td>
							<?php
				
								$myQuery = "SELECT w.time,UCASE(sb.name),IF(test=0,'-','TEST') FROM working_batches w,student_details sd,batch b,SUBJECT sb WHERE sd.batch_id = b.id AND w.batch_id=b.id AND sd.edutech_student_id=".$s1."
								AND work_date =CURDATE() AND w.sub_id=sb.id";
								
								$result=mysql_query($myQuery) or die($myQuery."<br/><br/>".mysql_error());;
								echo "<table border='1'>";
								echo "<b>Today's Time Table</b>";
								echo "<th>TIME</th>";							
								echo "<th>SUBJECT</th>";
								echo "<th>TEST</th>";
								
								while($row=mysql_fetch_array($result))
								{
									echo "<tr>";
									echo "<td>".$row[0]."</td>";
									echo "<td>".$row[1]."</td>";
									echo "<td>".$row[2]."</td>";								
									echo "</tr>";
								}
								echo "</table>";
							?>
						</td>
					</tr>
					
					<tr>
						<td>
							<div id="Show_OMR_Div">
								<div style="width:140px">
									<label id="OMR_label" style="font-size:14px;">Show OMR Sheet</label>
								</div>
								<div id="sheet">
									<table style="width: 10px;height: 110px; background-color:#FFFFFF;border:1px solid blue;">
										
										<tr style="height:100%;">
											<td >
												<div id="dv" style="height:300px;overflow:scroll;">
													
												</div>
												<input type="button" id="OMR_answer_submit" name="OMR_answer_submit" value="Submit" />
											</td>
										</tr>
									</table>
								</div>
							</div>
						</td>
					</tr>
					<tr>
						<td>
							<div id="OMR_result">
								<div id="OMR_result_declare">
									
								</div>
							</div>
						<td>
					</tr>
				</table>
					
			</div>
			
	</body>
</html>